name = "AvianRangeShapes"
uuid = "43758e65-c212-4f94-86cd-b19b0b1351d9"
authors = ["Michael Krabbe Borregaard <mkborregaard@sund.ku.dk> and contributors"]
version = "1.0.0-DEV"

[deps]
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
SkipNan = "aed68c70-c8b0-4309-8cd1-d392a74f991a"
SpreadingDye = "d2fc507f-b8c3-4645-b292-ec755ef5f34e"

[compat]
SpreadingDye = "1.0.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
